version: '3'
networks:
  database:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  postgres:
    image: postgres:14
    networks:
        database:
            ipv4_address: 172.20.0.5
    environment:
      POSTGRES_DB: "carrotocr"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "MQcjPndiWW"
  carrotocr:
    build: ./
    networks:
        database:
            ipv4_address: 172.20.0.6
    environment:
      - PYTHONUNBUFFERED=True
    ports:
      - "8000:8000"
    command: bash -c "python3 db_script.py && uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
  front:
    build: ../search_text_rename_file
    networks:
        database:
            ipv4_address: 172.20.0.7
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm run build && npm run start"
