version: '3'
networks:
  database:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  postgres:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
        database:
            ipv4_address: 172.20.0.5
    environment:
      POSTGRES_DB: "carrotocr"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "MQcjPndiWW"
      
  carrotocr:
    build: ./
    networks:
        database:
            ipv4_address: 172.20.0.6
    environment:
      - PYTHONUNBUFFERED=True
    command: bash -c "python3 db_script.py && uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 99999 --ws-ping-timeout 99999"
    depends_on:
      - postgres
      
  front:
    build: ../search_text_rename_file
    networks:
        database:
            ipv4_address: 172.20.0.7
    command: bash -c "npm start"
    
  nginx:
    image: nginx:latest
    networks:
        database:
            ipv4_address: 172.20.0.8
    depends_on:
      - carrotocr
      - front
      - postgres
    ports:
      - '80:80'
    volumes:
      - ../search_text_rename_file/nginx.conf:/etc/nginx/nginx.conf
