version: '3'

services:
  web:
    image: fa4stik/carrotocr_web
    env_file:
      - '.env'
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    image: fa4stik/carrotocr_back
    command: sh -c "sleep 5 && python3 /carrotocr/db_script.py && python3 /carrotocr/src/main.py"
    env_file:
      - '.env'
    depends_on:
      - postgres
    volumes:
      - ./LOCAL_DATA:/carrotocr/LOCAL_DATA
    ports:
      - "39781:8000"

  postgres:
    image: postgres:14
    env_file:
      - '.env'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "6000:5432"